jenkins_scraper/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from rest_api import urls as api_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    # path('api/', include(api_urls)),
]

main_app/jenkins_statistics/urls.py
from django.conf import settings
from django.views.static import serve
from django.urls import include, path, re_path
from django.conf.urls.static import static

from . import views

app_name = 'jenkins_statistics'
urlpatterns = [
    path('', views.index, name='index'),
    path('test_results', views.test_results, name='test_results'),
    path('test_failures', views.test_failures, name='test_failures'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/main_app/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_api import urls as api_urls


app_name = 'main_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('jenkins_statistics.urls', namespace='statistics')),
    path('api/', include(api_urls))
]

main_app/jenkins_statistics/models.py
import django.utils
from django.db import models


class Pipeline(models.Model):
    pipeline_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.pipeline_name


class Job(models.Model):
    job_name = models.CharField(max_length=100)
    pipeline = models.ForeignKey(Pipeline, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('job_name', 'pipeline')

    def __str__(self):
        return self.job_name


class Build(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    build_number = models.IntegerField(default=1)
    build_timestamp = models.DateTimeField(default=django.utils.timezone.now)

    class Meta:
        unique_together = ('job', 'build_number')


class JobResults(models.Model):
    pipeline = models.ForeignKey(Pipeline, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    build = models.ForeignKey(Build, on_delete=models.CASCADE)
    build_url = models.CharField(max_length=100)
    build_result = models.IntegerField(default=1)
    build_git_sha = models.CharField(max_length=100, null=True)

    class Meta:
        unique_together = ('pipeline', 'job', 'build')

    def __str__(self):
        return str(self.build_result)


class JobFailures(models.Model):
    pipeline = models.ForeignKey(Pipeline, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    build = models.ForeignKey(Build, on_delete=models.CASCADE)
    job_result = models.ForeignKey(JobResults, on_delete=models.CASCADE)
    error_type = models.CharField(max_length=100)
    error_file = models.CharField(max_length=100, null=True)
    error_message = models.CharField(max_length=3000)

    def __str__(self):
        return str(self.error_type)

main_app/jenkins_statistics/views.py
import json
import pandas as pd
from django.shortcuts import render

from .models import Pipeline, Job, Build, JobResults, JobFailures

id_to_job_dict = {}
id_to_build_dict = {}
id_to_pipeline_dict = {}
id_to_job_result_dict = {}
build_numbers_by_pipelines = {}


def index(request):
    job_results_dict = {}
    job_results_queryset = JobResults.objects.values()

    for job_result in job_results_queryset:
        if not id_to_pipeline_dict.get(job_result['pipeline_id']):
            pipeline = Pipeline.objects.get(id=job_result['pipeline_id'])
            id_to_pipeline_dict[job_result['pipeline_id']] = pipeline
        if not id_to_job_dict.get(job_result['job_id']):
            job = Job.objects.get(id=job_result['job_id'])
            id_to_job_dict[job_result['job_id']] = job
        if not id_to_build_dict.get(job_result['build_id']):
            build = Build.objects.get(id=job_result['build_id'])
            id_to_build_dict[job_result['build_id']] = build
        pipeline = id_to_pipeline_dict.get(job_result['pipeline_id'])
        job = id_to_job_dict.get(job_result['job_id'])
        build = id_to_build_dict.get(job_result['build_id'])
        if not job_results_dict.get(pipeline.pipeline_name):
            job_results_dict[pipeline.pipeline_name] = {}
            build_numbers_by_pipelines[pipeline.pipeline_name] = []
        if not job_results_dict.get(pipeline.pipeline_name).get(job.job_name):
            job_results_dict[pipeline.pipeline_name][job.job_name] = []
        job_results_dict[pipeline.pipeline_name][job.job_name].append({'pipeline_name': pipeline.pipeline_name,
                                                                       'job_name': job.job_name,
                                                                       'build_number': build.build_number,
                                                                       'build_url': job_result['build_url'],
                                                                       'build_result': job_result['build_result'],
                                                                       'build_git_sha': job_result['build_git_sha']})
        build_numbers_by_pipelines[pipeline.pipeline_name].append(build.build_number)
    for pipeline_name in job_results_dict:
        pipeline_build_numbers = build_numbers_by_pipelines[pipeline_name]
        build_numbers_by_pipelines[pipeline_name] = sorted(list(set(pipeline_build_numbers)), reverse=True)
        job_names = job_results_dict.get(pipeline_name)
        job_names_order = ['check_files', 'aaaa', 'check_requirements', 'run_tests', 'scrap_data_to_db']
        ordered_job_names = {}

        if len(job_names.keys()) > 1:
            for jn in job_names_order:
                ordered_job_names[jn] = job_names[jn]
        else:
            ordered_job_names = job_names

        for job_name, values in ordered_job_names.items():
            job_results_dict[pipeline_name][job_name] = sorted(values, key=lambda item: item['build_number'])
    context = {
        'job_results_dict': json.dumps(job_results_dict),
        'build_numbers': json.dumps(build_numbers_by_pipelines)
    }
    return render(request, 'index.html', context)


def test_results(request):
    job_failures_dict = []
    job_results_with_foreign_keys_joined = JobResults.objects.select_related('pipeline') \
        .select_related('job').select_related('build').all()

    for jr in job_results_with_foreign_keys_joined:
        job_failures_dict.append({'pipeline_name': jr.pipeline.pipeline_name,
                                  'build_timestamp': jr.build.build_timestamp.strftime('%m/%d/%Y'),
                                  'build_result': jr.build_result
                                  })
    df = pd.DataFrame(job_failures_dict)
    group_df = df.groupby(['pipeline_name', 'build_timestamp'])
    result_counts = group_df['build_result'].apply(lambda x: (x == 0).sum())
    total_counts = group_df['build_result'].count()
    percentage = round((result_counts / total_counts) * 100, 2)
    result_df = pd.DataFrame({'percentage': percentage}).reset_index()
    df = pd.merge(group_df.size().reset_index(), result_df, on=['pipeline_name', 'build_timestamp'], how='left')
    df.columns = ['pipeline_name', 'build_timestamp', 'total_builds', 'percentage']
    df_to_dict = df.to_dict('records')
    result_dict = {}
    for record in df_to_dict:
        if not result_dict.get(record.get('pipeline_name')):
            result_dict[record.get('pipeline_name')] = {'build_timestamp': [],
                                                        'total_builds': [],
                                                        'percentage': []}
        result_dict[record.get('pipeline_name')]['build_timestamp'].append(record['build_timestamp'])
        result_dict[record.get('pipeline_name')]['total_builds'].append(record['total_builds'])
        result_dict[record.get('pipeline_name')]['percentage'].append(record['percentage'])
    return render(request, 'test_results.html', {'df': json.dumps(result_dict)})


def test_failures(request):
    job_failures_dict = {}
    job_failures_queryset = JobFailures.objects.values()

    for job_failure in job_failures_queryset:
        if not id_to_pipeline_dict.get(job_failure['pipeline_id']):
            pipeline = Pipeline.objects.get(id=job_failure['pipeline_id'])
            id_to_pipeline_dict[job_failure['pipeline_id']] = pipeline
        if not id_to_job_dict.get(job_failure['job_id']):
            job = Job.objects.get(id=job_failure['job_id'])
            id_to_job_dict[job_failure['job_id']] = job
        if not id_to_build_dict.get(job_failure['build_id']):
            build = Build.objects.get(id=job_failure['build_id'])
            id_to_build_dict[job_failure['build_id']] = build
        if not id_to_job_result_dict.get(job_failure['job_result_id']):
            job_result = JobResults.objects.get(id=job_failure['job_result_id'])
            id_to_job_result_dict[job_failure['job_result_id']] = job_result

        pipeline = id_to_pipeline_dict.get(job_failure.get('pipeline_id'))
        job = id_to_job_dict.get(job_failure.get('job_id'))
        build = id_to_build_dict.get(job_failure.get('build_id'))
        job_result = id_to_job_result_dict.get(job_failure.get('job_result_id'))
        if not job_failures_dict.get(pipeline.pipeline_name):
            job_failures_dict[pipeline.pipeline_name] = {}
        if not job_failures_dict.get(pipeline.pipeline_name).get(job.job_name):
            job_failures_dict[pipeline.pipeline_name][job.job_name] = []
        job_failures_dict[pipeline.pipeline_name][job.job_name].append({'pipeline_name': pipeline.pipeline_name,
                                                                        'job_name': job.job_name,
                                                                        'build_number': build.build_number,
                                                                        'build_result': job_result.build_result,
                                                                        'build_timestamp': build.build_timestamp,
                                                                        'build_url': job_result.build_url,
                                                                        'error_type': job_failure.get('error_type'),
                                                                        'error_file': job_failure.get('error_file'),
                                                                        'error_message': job_failure.get('error_message')})
    return render(request, 'test_failures.html', {'job_failures_dict': job_failures_dict})

main_app/jenkins_statistics/templates/base.html
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Jenkins Statistics</title>
</head>
<body>
    {% block body_header %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Jenkins Statistics</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jenkins_statistics:test_results' %}">Test results</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jenkins_statistics:test_failures' %}">Test failures</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block body_content %}
    {% endblock %}
</body>

main_app/jenkins_statistics/templates/index.html
{% extends 'base.html' %}

{% block body_header %}
    <link href='https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css' rel='stylesheet'>
    <!-- Load d3.js -->
    <script src='https://d3js.org/d3.v4.js'></script>
    <!-- Load color palettes -->
    <script src='https://d3js.org/d3-scale-chromatic.v1.min.js'></script>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css' integrity='sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA==' crossorigin='anonymous' referrerpolicy='no-referrer' />
    <body onload='plot_manager(15)'>
{% endblock %}

{% block body_content %}
    <div class='vertical-menu toggled d-none' id='vertical-menu'></div>
    <button class='hide-button btn btn-info float-right sticky-top' onclick='show_menu()'><i class='hide-button bi bi-list'>Menu</i></button>

    <div>
        <h5>This page visualizes key statistics for Jenkins builds.
            Use the information to understand build trends and identify potential issues.</h5>
        <p>Use menu on the right to quickly navigate to pipelines.</p>
        <p>Understanding the Plot:<br>
        Pipeline name: Click pipeline name to navigate to this pipeline in Jenkins.<br>
        X-axis: Job names in particular pipeline<br>
        Y-axis: Represents the builds. Click on number to navigate to this build in Jenkins.<br>
        Squares/Rectangles: Each square/rectangle represents a specific Jenkins build result.
            Hover over square to get detailed info about job build.</p>
    </div>

    <div class='inBody'>
        <br>
        <form id='buildsForm'>
            <label class='text' for='buildsSelect'>Choose amount of builds to plot:</label>
            <input type='text' name='builds' id='answerInput' list='buildsSelect' placeholder='Enter here specific number of builds'>
            <datalist id='buildsSelect'>
                <option data-value='15'>15 builds</option>
                <option data-value='30'>30 builds</option>
                <option data-value='60'>60 builds</option>
            </datalist>
            <input type='hidden' name='answer' id='answerInput-hidden' value='15'>
            <input type='submit' class='btn btn-info'>
        </form>

        <div id='plot'></div>
        <div id='legend'></div>
    </div>

    <script>
        window.addEventListener('scroll', menuHighlighter);
        window.addEventListener('onclick', menuHighlighter);

        function menuHighlighter() {
            let scrollY = window.pageYOffset;
            const sections = document.querySelectorAll('section[id]');

            sections.forEach(current => {
                const sectionHeight = current.offsetHeight;
                const sectionTop = (current.getBoundingClientRect().top + window.pageYOffset) - 50;
                var sectionId = current.getAttribute('id');

                if (scrollY > sectionTop && scrollY <= sectionTop + sectionHeight) {
                    document.querySelector('.vertical-menu a[href*=' + sectionId + ']').classList.add('active');
                } else {
                    document.querySelector('.vertical-menu a[href*=' + sectionId + ']').classList.remove('active');
                }
            });
        }

        function show_menu() {
            var menus = document.getElementsByClassName('vertical-menu');

            for (var menu of menus) {
                if (menu.classList.contains('d-none')) {
                    menu.classList.remove('d-none');
                }
                else {
                    menu.classList.add('d-none');
                }
            }
        }

        var input = document.querySelectorAll('input');
        for (var i=0; i<input.length; i++) {
            if (input[i].placeholder !== '') {
                input[i].setAttribute('size', input[i].getAttribute('placeholder').length);
            }
        }

        document.querySelector('input[list]').addEventListener('input', function(e) {
            var input = e.target,
                list = input.getAttribute('list'),
                options = document.querySelectorAll('#' + list + ' option'),
                hiddenInput = document.getElementById(input.getAttribute('id') + '-hidden'),
                label = input.value;

            hiddenInput.value = label;
            for(var i = 0; i < options.length; i++) {
                var option = options[i];

                if(option.innerText === label) {
                    hiddenInput.value = option.getAttribute('data-value');
                    break;
                }
            }
        });

        document.getElementById('buildsForm').addEventListener('submit', function(e) {
            clear_svg_call_plots_manager();
            e.preventDefault();
        });

        const build_results = {
            0: 'SUCCESS',
            1: 'FAILURE',
            2: 'UNSTABLE',
            3: 'ABORTED'
        }

        function convert_result(result)
        {
            return build_results[result];
        }

        function clear_svg_call_plots_manager()
        {
            document.getElementById('plot').innerHTML = '';
            document.getElementById('vertical-menu').innerHTML = '';
            let buildsAmount = document.getElementById('answerInput-hidden').value;
            plot_manager(buildsAmount);
        }

        function plot_manager(filter_num)
        {
            const raw_data = JSON.parse('{{job_results_dict|safe}}');
            const build_numbers = JSON.parse('{{build_numbers|safe}}');

            for (var pipeline_name in raw_data)
            {
                create_plot(pipeline_name,
                           raw_data[pipeline_name],
                           build_numbers,
                           filter_num);
            }
        }

        function create_plot(pipeline_name, data, build_numbers, filter_num)
        {
            // Create menu entry
            var menu = document.getElementById('vertical-menu');
            var a_tag = document.createElement('a');
            a_tag.href = `#${pipeline_name}`;
            a_tag.class = 'active';
            a_tag.text = pipeline_name;
            menu.appendChild(a_tag);

            // Calculate height of graph(approx. +200 every 30 builds) - default 700 for 15 builds
            var calculatedHeight = 700 + 200 * Math.floor(filter_num / 30);

            // Set the dimensions and margins of the graph
            var margin = {top: 100, right: 50, bottom: 400, left: 50},
                width = window.innerWidth - margin.left - margin.right,
                height = calculatedHeight - margin.top - margin.bottom;

            // Append the svg object to the body of the page
            var svg = d3.select('#plot')
                .append('section')
                .attr('id', pipeline_name)
                .append('svg')
                .attr('width', width + margin.left + margin.right)
                .attr('height', height + margin.top + margin.bottom)
                .append('g')
                .attr('transform', 'translate(' + margin.left + ',' + margin.top + ')');

            const bn = [... new Set(build_numbers[pipeline_name].slice(0, filter_num))].sort((a, b) => a - b).reverse();
            let sliced_data = [];
            for (let i in bn)
            {
                for (let job_name in data) {
                        var filteredData = data[job_name].filter(function(result) {
                            return result.build_number === bn[i];
                        });
                        sliced_data.push(...filteredData);
                    }
            }
            sliced_data.reverse();

            var myGroups = d3.map(sliced_data, function(d){return d.job_name;}).keys();
            var myVars = d3.map(sliced_data, function(d){return d.build_number;}).keys();

            // Build X scales and axis:
            var xAxis = d3.scaleBand().range([ 0, width ]).domain(myGroups).padding(0.05);
            svg.append('g')
                .style('font-size', 15)
                .attr('transform', 'translate(0,' + height + ')')
                .call(d3.axisBottom(xAxis).tickSize(0))
                .call(g => g.select('.domain').remove())
                .selectAll('text')
                .style('text-anchor', 'end')
                .attr('transform', 'rotate(-90)')


            // Build Y scales and axis:
            var yAxis = d3.scaleBand().range([ height, 0 ]).domain(myVars).padding(0.05)
            svg.append('g')
                .style('font-size', 10)
                .call(d3.axisLeft(yAxis).tickSize(0))
                .call(g => g.select('.domain').remove())
                .selectAll('text')
                .style('fill', 'blue')
                .on('mouseover', function(d) {d3.select(this).style('cursor', 'pointer');})
                .on('mouseout', function(d) {d3.select(this).style('cursor', 'default');})
                .on('click', function(d) {window.open(`http://localhost:8080/job/${pipeline_name}/${d}`)});

            // Build color scale
            var colors = ['green', 'red', 'yellow', 'gray']

            // Create a tooltip
            var tooltip = d3.select(`#${pipeline_name}`)
                .append('div')
                .style('opacity', 0)
                .attr('class', 'tooltip')
                .style('background-color', 'white')
                .style('border', 'solid')
                .style('border-width', '2px')
                .style('border-radius', '5px')
                .style('padding', '5px')

            // Functions that change the tooltip when user hover / move / leave a cell
            var mouseover = function(d)
            {
                tooltip.style('opacity', 1)
                d3.select(this).style('stroke', 'black').style('opacity', 1)
            }
            var mousemove = function(d)
            {
                var tooltipText = '<br>Pipeline: ' + d.pipeline_name + '<br>Job: ' + d.job_name + '<br>Build: ' + d.build_number + '<br>Result: ' + convert_result(d.build_result)
                tooltip.html(tooltipText)
                            .style("top", (event.pageY + 40) + "px")
                            .style("left",(event.pageX + 20) + "px")
            }
            var mouseleave = function(d)
            {
                tooltip.style('opacity', 0)
                var strokeStyle = function () {
                    return 'none'
                }
                d3.select(this).style('stroke', strokeStyle).style('opacity', 0.8)
            }

            // Add the squares
            svg.selectAll()
                .data(sliced_data, function(d) {return d.job_name + ':' + d.build_number;})
                .enter()
                .append('rect')
                .attr('x', function(d) { return xAxis(d.job_name) })
                .attr('y', function(d) { return yAxis(d.build_number) })
                .attr('rx', 4)
                .attr('ry', 4)
                .attr('width', xAxis.bandwidth())
                .attr('height', yAxis.bandwidth())
                .attr('data-legend',function(d) { return d.build_result})
                .style('fill', function(d) {return colors[d.build_result]})
                .style('stroke-width', 4)
                .style('stroke', function (d) {
                    return 'none'
                })
                .style('opacity', 0.8)
                .on('mouseover', mouseover)
                .on('mousemove', mousemove)
                .on('mouseleave', mouseleave)
                .on('click', 'mouseclick')
            // Add title to graph
            svg.append('text')
                .attr('x', 0)
                .attr('y', -50)
                .attr('text-anchor', 'left')
                .style('font-size', '22px')
                .text(`Pipeline ${pipeline_name} results`)
                .style('fill', 'blue')
                .on('mouseover', function(d) {d3.select(this).style('cursor', 'pointer');})
                .on('mouseout', function(d) {d3.select(this).style('cursor', 'default');})
                .on('click', function(d) {window.open(`http://localhost:8080/job/${pipeline_name}`)});
        }
    </script>

    <style>
        html {
            scroll-behavior: smooth;
        }

        #main_content {
            margin: 2%;
        }

        .vertical-menu {
            width: 10%;
            position: fixed;
            right: 0;
            top: 10%;
        }

        .vertical-menu a {
            background-color: #eee;
            color: black;
            display: block;
            padding: 12px;
            text-decoration: none;
        }

        .vertical-menu a:hover {
            background-color: #ccc;
        }

        .vertical-menu a.active {
            background-color: #04AA6D;
            color: white;
        }

        h5 {
            padding: 20px;
            color: #333;
        }

        p, .text {
            padding-left: 20px;
            font-family: Arial, sans-serif;
            font-size: 16px;
            color: #333;
        }
    </style>
{% endblock %}